openapi: 3.0.0
info:
  title: My API Documentation
  version: 1.0.0

paths:
  /check-email:
    post:
      summary: Validates an email address
      description: |
        This endpoint checks if an email address is valid using multiple methods, including:
        - Regex pattern matching
        - MX record lookup
        - Temporary email domain check
        - Limited email server connectivity check
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@domain.com
      responses:
        200:
          description: Email is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email is valid"
        400:
          description: Invalid email address or other validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: |
                      "Invalid email"

        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
      tags:
        - Email Validation
